[package]
name = "rbedic"
version = "0.1.1"
authors = ["Ivan Dzhonev <ivan.dzhonev at gmail.com>"]

[dependencies]
gtk = { version = "0.3", features = ["v3_16"] }
gdk = "0.7"

log = "0.3"
env_logger = "0.3"

lazy_static = "1"
regex = "0.2"
